model:
  nhead: 4
  num_layers: 4
  d_model: 16
  dim_feedforward: 64
  dropout: 0.0

training:
  batch_size: 64
  lr: 1e-3
  epochs: 5000
  optimizer: adam
  loss: mse
  train_fraction: 0.7
  val_fraction: 0.15
  early_stopping:
    enabled: true
    patience: 20
    delta: 1e-4

masking:
  type: random
  percentage: 0.1

data:
  raw_path: 'Datasets/JM_data/pool_ex8_PCs.h5'
  conditions_path: 'sensory_contexts_data.npy'
  processed_dir: "processed_data"
  input_dim: 20
  sequence_length: 5

seed: 42