model:
  nhead: 4
  num_layers: 4
  d_model: 256
  dropout: 0.0

training:
  batch_size: 128
  lr: 3e-4
  epochs: 2
  optimizer: adam
  loss: cross_entropy
  train_fraction: 0.7
  val_fraction: 0.15
  early_stopping:
    enabled: true
    patience: 30
    delta: 1e-4
  single_instance_overfit: True
  two_tasks: True

masking:
  type: random
  percentage: 0.1
  weighted: True
  learnable_mask_embedding: True

data:
  process_data_first: true
  one_hot: true
  raw_path: 'Datasets/JM_data/pool_ex8_PCs.h5'
  conditions_path: 'sensory_contexts_data.npy'
  processed_dir: "Datasets/processed-10-20/"
  sequence_length: 10
  input_dim: 20

seed: 42