model:
  nhead: 4
  num_layers: 4
  d_model: 8
  dim_feedforward: 32
  dropout: 0.0

training:
  single_instance_overfit: True
  batch_size: 1
  lr: 3e-3
  epochs: 500
  optimizer: adam
  loss: cross_entropy
  train_fraction: 0.7
  val_fraction: 0.15
  early_stopping:
    enabled: true
    patience: 30
    delta: 1e-5

masking:
  type: random
  percentage: 0.1

data:
  process_data_first: true
  one_hot: True
  raw_path: 'Datasets/JM_data/pool_ex8_PCs.h5'
  conditions_path: 'sensory_contexts_data.npy'
  processed_dir: "Datasets/one_hot_processed/"
  input_dim: 13
  sequence_length: 10

seed: 42